### ISSUE TITLE
切换线路后中间显示Blocked Plug-in

### ISSUE THREAD

**Issue by MachelleZhang** [iodefog/VipVideo#1]
无法播放呢！

**Comment by iodefog** [comment]
1.系统偏好设置>其他/ Flash Player>高级>全部删除
     按下“全部删除”按钮
     安装Adobe Flash Player
    http://get.adobe.com/flashplayer/
    退出Safari。
    重新启动计算机。重新启动Safari。

2.启用插件
    Safari>首选项>安全性
     互联网插件>“允许所有其他插件

**Comment by iodefog** [comment]
那不应该能播放了吗？你那边还提示什么？

**Comment by 631068264** [comment]
网站说我没有安装flash插件  我用Chrome好好的。safari 插件栏没找到flash插件 可能你没看到 截图有

**Comment by iodefog** [comment]
你把地址copy到safari下试试。提示安装你就安装。走一下流程。步骤就这些，如果还不行，就再查查具体原因吧

**Comment by 631068264** [comment]
都试过不行

**Comment by black1997** [comment]
老铁，给份源码学习一下呗。
