### ISSUE TITLE
支持 Windows 版本了

### ISSUE THREAD

**Issue by phobal** [iodefog/VipVideo#12]
借楼主风水宝地一用，打个小广告  
当看到楼主这个神器之后，我看视频再也不打开浏览器看了，包括非 VIP 才能看的资源，身边很多朋友看到我使用这个软件在看视频，而且还可以免费去广告看 VIP 资源，也很想要这个软件，可以他们大多用的 windows, 很尴尬啊，所以我就萌生了一个做一个 Windows 版本的想法，这2天刚换工作在家还没去上班就想起这事来了，所以就写了一个支持 windows 版本的，当然也支持 mac 和 Ubuntu，欢迎大家下载体验，https://github.com/phobal/ivideo

**Comment by iodefog** [comment]
牛

**Comment by JeanKit** [comment]
9.9K了已经
